### ISSUE TITLE
Simurg'un işlem yapması çok uzun sürüyor.

### ISSUE THREAD

**Issue by zekiahmetbayar** [clutchsoftware/Simurg#9]
Önceki versiyonlara oranlar Simurg'un çalışması çok uzun sürüyor.

**Comment by tugbaficici** [comment]
Bu sorunu yaratan fonksiyon tespit edildi. Sorunun kelime ayırma fonksiyonlarından olduğu görüldü. Bu fonksiyonlar comboBox'a taşınarak her zaman değil, kullanıcı istediği zaman çalışmaktadır. main.py güncellendi.
